# Generated by Django 5.2.17 on 2026-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('bio', models.TextField(default='Hey there! I am using Postly.')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover_photos/')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='connections_of', to='social.user')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_of', to='social.user')),
                ('following', models.ManyToManyField(blank=True, related_name='following_of', to='social.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
