# Generated by Django 5.2.17 on 2026-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_user_connections_post_comment_postshare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileshare',
            name='profile_user',
        ),
        migrations.RemoveField(
            model_name='profileshare',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='profileshare',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PostShare',
        ),
        migrations.DeleteModel(
            name='ProfileShare',
        ),
    ]
