# Generated by Django 5.2.17 on 2026-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_from_user_notification_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
