# Generated by Django 5.2.17 on 2026-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_notification_notification_type_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
