# Generated by Django 5.2.17 on 2026-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
